### ISSUE TITLE
Update components with potential security vulnerabilities

### ISSUE THREAD

**Issue by frncesc** [gencat/gobierto-budgets-comparator-gen-cat#81]
Hola,
GitHub nos reporta una alerta de seguridad relacionada con el componente "nokogiri" en versiones anteriores a la 1.8.1 (la actualmente requerida por Gemfile.lock es la 1.6.1).
En el [análisis completo de dependencias](https://github.com/gencat/gobierto-budgets-comparator-gen-cat/network/dependencies) aparecen también otros elementos con vulnerabilidad potencial declarados en [Gemfile.lock](https://github.com/gencat/gobierto-budgets-comparator-gen-cat/blob/master/Gemfile.lock).
Sería conveniente actualizar las versiones de estas dependencias para evitar cualquier riesgo.

**Comment by ferblape** [comment]
Hecho
